### PR TITLE
Propagate announce

### PR DESCRIPTION
**Pull request by folkertdev**

### CODE REVIEW

**Comment by davidv1992** [comment]
Looking through it, this definitely is an approach that works, and has the advantage of being able to use allocations where available. However, in the interest of keeping the interface of users of the library simpler I would prefer to handle TLV propagation fully internally. What would be the disadvantages/problems with that?

**Comment by folkertdev** [comment]
well you'd need to transfer this information during bmca right, there is no other way to exchange information between the ports. But I think we can make it more abstract so that statime-linux doesn't need custom knowledge of what a TLV is. Or in any case less knowledge

**Comment by davidv1992** [comment]
Yes, if we want to do it internally we need to do that during the bmca, but that is not what this code is doing.

**Comment by davidv1992** [comment]
Also, taking a second look, I think this uncoditionally forwards all tlvs, even those received from masters that aren't the current best master (at least when they are received on the same port), which I think is not what the spec intends.

**Comment by folkertdev** [comment]
allright, I need another "vibe check" here. This feature turns out to add a lot of extra complexity, now there is also some filtering logic that escapes into statime-linux. Not very happy about it, but don't currently see another way

**Comment by davidv1992** [comment]
I think we should make the effort to at least keep the filtering inside the library. I think the best way to do that is to add a propagate-tlv action to the portactions. This should then contain some opaque object with both the tlv and the identifier of the master it came from. (this should then of course allow for changing of the backing buffer, and in std mode it would probably be nice if you can convert it to an owned one, perhaps similar to how `std::borrow::Cow` works).

Then either a reference to a list of these can be passed to the announce timer function, which just always tries to consume all of them (and drops the ones not consumed to minimize retransmission delay). Or the announce timer function can take (a reference to) an iterator as input. In both cases, I think it is easiest to then have the announcing port doing the filtering, since that is the point at which the correct tlvs need to be forwarded. I think the parent dataset contains sufficient information for it to do this.

**Pull request closed without merging**
